### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MeRichard123** [RichTools/richbuild#1]
- [x] Ability to exclude files from compilation
- [ ] Better package handling
- [ ] Incremental building (compare modified date)
